### ISSUE TITLE
Search and use the previous images

### ISSUE THREAD

**Issue by bashirnoori** [textpattern/com_article_image#4]
This is a very nice plugin, I've a new idea to add a new **ajax search box** option to find uploaded images by name and use that article image.
**Reason:** Blog websites are using more images, like one of my client's website has more than >6k images, now they are going to prevent from uploading duplicated images, for example if there is a news of Facebook, they already uploaded facebook-logo.jpg and instead of uploading that image again, they may search Facebook and use that.
I installed [fh-article-image-selector](https://textpattern.org/plugins/1103/fh_article_image_selector) plugin to chose article image from drop down list, but every time when they go to the new article option, those >6k image names will be loaded to the drop down list which take more time to load !

**Comment by bloatware** [comment]
Hi Bashir, thank you for the idea. We actually hope to improve the images workflow in the next txp release, but I will think of implementing it in `com_article_image` if core takes too much time.

**Comment by bloatware** [comment]
Seemingly, `com_article_image` can do it, just check that its `Image search fields` pref contains `name`.
